### ISSUE TITLE
The returned value of cat_title is inconsistent

### ISSUE THREAD

**Issue by tai271828** [tai271828/attendees-analyzer#2]
When I tried to implement the unit test of [cat_title](https://github.com/tai271828/attendees-analyzer/blob/master/atta/cleaner/title.py) with [the test data](https://github.com/tai271828/attendees-analyzer/blob/master/test/data/title-category.csv), I noted the returned value is not always consistent.

# Steps To Reproduce

```
#!/usr/bin/env python3
from title import cat_title
print(cat_title('ap'))
```
Execute this code snippet for several times (> 5 times). You may want to save this snippet under `atta/cleaner/` as a `xx.py` file. `chmod +x xx.py` to make it executable and then `./xx.py` to execute it.

# Expected Result
The code snippet always returns a string `Engineer`.

# Actual Result
You will get either `Engineer` or `Developer` randomly.

Reproducing rate: 100 %

**Comment by zztin** [comment]
This cannot be reproduced on my os x. The test code snippet results in Developer every time.

**Comment by tai271828** [comment]
The PR looks good[1]. Thanks @zztin !

[1]

```
attendees-analyzer/test⟫ ./title.py 
.
----------------------------------------------------------------------
Ran 1 test in 0.011s

OK
```
