### ISSUE TITLE
Setup Drone CI for the project

### ISSUE THREAD

**Issue by tai271828** [tai271828/attendees-analyzer#26]
In the Oct sprint we decided to use drone ci to be the infrastructure.

**Comment by tai271828** [comment]
A related PR https://github.com/tai271828/attendees-analyzer/pull/29

@Lee-W  you may want to relate the issue number in your git commit messages in the future. Github will automatically relate the PR per the issue.

**Comment by tai271828** [comment]
The very first drone CI run and it passes! https://cloud.drone.io/tai271828/attendees-analyzer/1

**Comment by Lee-W** [comment]
Ah yes, I forgot to do so. But, I personally like to mention the related issue or pr in the description of that pr instead of adding them to git commit directly.
