### ISSUE TITLE
Rename the command entry

### ISSUE THREAD

**Issue by tai271828** [tai271828/attendees-analyzer#27]
For now atta is not a name good enough because this tool is not limited to be used in attendee analysis but for all post-event report. A name like `report generator` or `rg-cli` may be better in the long run. In the discussion of Oct sprint the roadmap of the refactoring could be:

- [x] Rename `atta` to be `rg-cli`
- [x] Refactor and rename the package from `atta` to be `rg`

**Comment by Lee-W** [comment]
Since #28 is merged, close this issue.
